api/src/main/java/dev/httpmarco/polocloud/api/CloudAPI.java
api/src/main/java/dev/httpmarco/polocloud/api/packets/CloudComponentPacketHelper.java
api/src/main/java/dev/httpmarco/polocloud/api/packets/player/CloudAllPlayersPacket.java
api/src/main/java/dev/httpmarco/polocloud/api/packets/player/CloudPlayerPacket.java
api/src/main/java/dev/httpmarco/polocloud/api/packets/player/CloudPlayerRegisterPacket.java
api/src/main/java/dev/httpmarco/polocloud/api/packets/player/CloudPlayerServiceChangePacket.java
api/src/main/java/dev/httpmarco/polocloud/api/packets/player/CloudPlayerUnregisterPacket.java
api/src/main/java/dev/httpmarco/polocloud/api/player/CloudPlayer.java
api/src/main/java/dev/httpmarco/polocloud/api/player/CloudPlayerProvider.java
base/src/main/java/dev/httpmarco/polocloud/base/CloudBase.java
base/src/main/java/dev/httpmarco/polocloud/base/player/CloudPlayerImpl.java
base/src/main/java/dev/httpmarco/polocloud/base/player/CloudPlayerProviderImpl.java
base/src/main/java/dev/httpmarco/polocloud/base/services/CloudServiceProviderImpl.java
instance/src/main/java/dev/httpmarco/polocloud/runner/CloudInstance.java
instance/src/main/java/dev/httpmarco/polocloud/runner/player/InstanceCloudPlayerImpl.java
instance/src/main/java/dev/httpmarco/polocloud/runner/player/InstanceCloudPlayerProvider.java
instance/src/main/java/dev/httpmarco/polocloud/runner/services/InstanceServiceProvider.java
plugin/src/main/java/dev/httpmarco/polocloud/velocity/VelocityPlatform.java
plugin/src/main/java/dev/httpmarco/polocloud/velocity/listener/PlayerChooseInitialServerListener.java
plugin/src/main/java/dev/httpmarco/polocloud/velocity/listener/PlayerDisconnectListener.java
plugin/src/main/java/dev/httpmarco/polocloud/velocity/listener/PlayerServerSwitchListener.java
plugin/src/main/java/dev/httpmarco/polocloud/velocity/listener/PreLoginListener.java

Started CloudPlayer implementation

---

base/src/main/resources/server-files/velocity/velocity.toml

changed default motd

---

base/src/main/resources/server-files/bungeecord/config.yml

changed default motd in bungeecord

---

base/src/main/java/dev/httpmarco/polocloud/base/services/ServiceCommand.java
base/src/main/java/dev/httpmarco/polocloud/base/terminal/commands/CommandService.java
instance/src/main/java/dev/httpmarco/polocloud/runner/services/InstanceCloudService.java

added execute command & new subcommand argument

---

base/src/main/java/dev/httpmarco/polocloud/base/terminal/commands/CommandService.java

make Integers possible as argument again

fix command bug

---

base/src/main/java/dev/httpmarco/polocloud/base/groups/GroupCommand.java
base/src/main/java/dev/httpmarco/polocloud/base/services/ServiceCommand.java
base/src/main/java/dev/httpmarco/polocloud/base/templates/TemplateCommand.java
base/src/main/java/dev/httpmarco/polocloud/base/terminal/commands/CommandCompleter.java

- Handle right complete method
- Added auto completions
- Typos

Auto complete

---

addons/proxy-addon/build.gradle.kts
addons/proxy-addon/src/main/java/dev/httpmarco/polocloud/proxy/VelocityPlatformPlugin.java
addons/proxy-addon/src/main/java/dev/httpmarco/polocloud/proxy/config/Config.java
addons/proxy-addon/src/main/java/dev/httpmarco/polocloud/proxy/listener/ServerPostConnectListener.java
addons/proxy-addon/src/main/java/dev/httpmarco/polocloud/proxy/tablist/Tablist.java
addons/proxy-addon/src/main/java/dev/httpmarco/polocloud/proxy/tablist/TablistConfiguration.java
addons/proxy-addon/src/main/java/dev/httpmarco/polocloud/proxy/tablist/TablistManager.java
plugin/src/main/java/dev/httpmarco/polocloud/velocity/VelocityPlatform.java

change default motd & moved to external proxy-plugin

---

.idea/gradle.xml
addons/hubcommand-addon/build.gradle.kts
addons/hubcommand-addon/src/main/java/dev/httpmarco/polocloud/hubcommand/bungeecord/BungeeCordPlatformPlugin.java
addons/hubcommand-addon/src/main/java/dev/httpmarco/polocloud/hubcommand/bungeecord/command/HubCommand.java
addons/hubcommand-addon/src/main/java/dev/httpmarco/polocloud/hubcommand/configuration/ConfigManager.java
addons/hubcommand-addon/src/main/java/dev/httpmarco/polocloud/hubcommand/configuration/MessagesConfiguration.java
addons/hubcommand-addon/src/main/java/dev/httpmarco/polocloud/hubcommand/velocity/VelocityPlatformPlugin.java
addons/hubcommand-addon/src/main/java/dev/httpmarco/polocloud/hubcommand/velocity/command/HubCommand.java
addons/hubcommand-addon/src/main/resources/bungee.yml
settings.gradle.kts

Simple HubCommand-Addon for Velocity and Bungee, all messages are customizable

HubCommand-Addon

---

node/src/main/java/dev/httpmarco/polocloud/node/terminal/commands/NodeCommand.java
node/src/main/java/dev/httpmarco/polocloud/node/update/AutoUpdater.java

& block node update command if the update is already downloaded

added node update confirm command

---

polocloud-node/src/main/java/dev/httpmarco/polocloud/node/commands/impl/ShutdownCommand.java
polocloud-node/src/main/resources/i18n/polocloud-node_de.properties
polocloud-node/src/main/resources/i18n/polocloud-node_en.properties

Add translation to stop command

---

.gitignore
build.gradle.kts
gradle.properties
gradle/libs.versions.toml
polocloud-api/build.gradle.kts
polocloud-bom/build.gradle.kts
polocloud-common/build.gradle.kts
polocloud-daemon/build.gradle.kts
polocloud-gradle-structure/build.gradle.kts
polocloud-gradle-structure/settings.gradle.kts
polocloud-gradle-structure/src/main/kotlin/polocloud.base.gradle.kts
polocloud-gradle-structure/src/main/kotlin/polocloud.common.gradle.kts
polocloud-gradle-structure/src/main/kotlin/polocloud.publishing.gradle.kts
polocloud-installer/build.gradle.kts
polocloud-launcher/build.gradle.kts
polocloud-node/build.gradle.kts
settings.gradle.kts

Current Java version is Java 21 (LTS).
You should also check out the publishing plugin (polocloud.publishing.gradle.kts) in the gradle-structure directory and customize your information.

chore: update gradle setup

---

polocloud-node/build.gradle.kts

chore: update gradle dependencies

---

.github/workflows/gradle.yml
.github/workflows/release.yml
.github/workflows/snapshot.yml

remember to add secrets SONATYPE_USERNAME and SONATYPE_PASSWORD.
dont forget to enable [dependency graph](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/configuring-the-dependency-graph)

feat: add workflow

---

agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/local/LocalRuntime.kt
agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/local/terminal/JLine3Reading.kt
agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/local/terminal/Jline3Terminal.kt
agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/local/terminal/commands/impl/ServiceCommand.kt
agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/local/terminal/screen/ServiceScreenController.kt
agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/local/tracking/LocalServiceLogTrack.kt
agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/local/tracking/LocalTrack.kt

#325 Screen system

---

launcher/src/main/java/dev/httpmarco/polocloud/launcher/dependencies/DependencyProvider.java

Enable parallel downloading of dependencies for improved performance

---

agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/local/terminal/commands/impl/InfoCommand.kt

fix: improve memory calculation precision in InfoCommand

---

agent/src/main/kotlin/dev/httpmarco/polocloud/agent/configuration/AgentConfig.kt
agent/src/main/kotlin/dev/httpmarco/polocloud/agent/runtime/local/terminal/JLine3Reading.kt
agent/src/main/kotlin/dev/httpmarco/polocloud/agent/runtime/local/terminal/arguments/InputContext.kt
agent/src/main/kotlin/dev/httpmarco/polocloud/agent/runtime/local/terminal/arguments/type/IntArgument.kt
agent/src/main/kotlin/dev/httpmarco/polocloud/agent/runtime/local/terminal/arguments/type/LocaleArgument.kt
agent/src/main/kotlin/dev/httpmarco/polocloud/agent/runtime/local/terminal/setup/impl/GroupSetup.kt
agent/src/main/kotlin/dev/httpmarco/polocloud/agent/runtime/local/terminal/setup/impl/OnboardingSetup.kt
agent/src/main/resources/i18n/polocloud-agent_en.properties

Added default value for IntArgument
Boolean Status Line in AgentConfig
removed Todos
Changed TextArguments to Yes/No Arguments in OnboardingSetup
- #424

Improvements for OnBoardingSetup

---

.github/README.md
sdk/sdk-rust/README.md

Some adjustments on the README for the rust SDK

Rust sdk README

---

agent/src/main/kotlin/dev/httpmarco/polocloud/agent/runtime/local/LocalRuntimeTemplates.kt

/
Use createDirectories instead of createDirectory
#555
On my vps
/

fix: use createDirectories instead of createDirectory for target directory creation

---

addons/api/src/main/kotlin/dev/httpmarco/polocloud/addons/api/LegacyFormatter.kt
addons/notify/src/main/kotlin/dev/httpmarco/polocloud/addons/notify/platform/bungeecord/BungeecordPlatform.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/CloudSubCommand.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/ProxyConfiguration.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/bungeecord/BungeecordCloudCommand.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/bungeecord/BungeecordCloudSubCommand.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/bungeecord/BungeecordPlatform.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/bungeecord/BungeecordTablistUpdater.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/bungeecord/commands/InfoSubCommand.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/bungeecord/commands/ListSubCommand.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/bungeecord/commands/MaintenanceSubCommand.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/bungeecord/commands/PlayersSubCommand.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/bungeecord/commands/StartSubCommand.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/bungeecord/commands/StopSubCommand.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/bungeecord/events/BungeecordMotdUpdater.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/bungeecord/events/PlayerLoginEvent.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/velocity/VelocityCloudSubCommand.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/velocity/subcommands/InfoSubCommand.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/velocity/subcommands/ListSubCommand.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/velocity/subcommands/MaintenanceSubCommand.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/velocity/subcommands/PlayersSubCommand.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/velocity/subcommands/StartSubCommand.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/velocity/subcommands/StopSubCommand.kt

The notify and proxy addon works now with the platform bungeecord!
- added support for bungeecord
/ 
local cloud instance

Implemented: proxy addon bungeecord support + notify addon bungeecord support

---

agent/src/main/kotlin/dev/httpmarco/polocloud/agent/runtime/local/LocalCpuDetectionThread.kt

- NullPointerException in CPU Thread while shut down a service
- moved cpu variable
/ 
local cloud instance

Fix: `cpu` nullpointer exception

---

agent/src/main/kotlin/dev/httpmarco/polocloud/agent/grpc/GrpcServerEndpoint.kt
agent/src/main/kotlin/dev/httpmarco/polocloud/agent/runtime/Runtime.kt
agent/src/main/kotlin/dev/httpmarco/polocloud/agent/runtime/docker/DockerRuntime.kt
agent/src/main/kotlin/dev/httpmarco/polocloud/agent/runtime/k8s/KubernetesRuntime.kt
agent/src/main/kotlin/dev/httpmarco/polocloud/agent/runtime/local/LocalRuntime.kt
agent/src/main/kotlin/dev/httpmarco/polocloud/agent/stats/StatsGrpcService.kt
proto/src/main/proto/polocloud/v1/proto/stats_provider.proto
sdk/sdk-java/src/main/java/dev/httpmarco/polocloud/sdk/java/stats/StatsProvider.java
shared/src/main/kotlin/dev/httpmarco/polocloud/shared/stats/SharedStatsProvider.kt
shared/src/main/kotlin/dev/httpmarco/polocloud/shared/stats/Stats.kt

Implemented StatsGrpcService
- Added StatsProvider for java-sdk
- Implements grpc functions
Rest-API (Dashboard)
local cloud instance

Implemented: StatsGrpcService

---

agent/src/main/kotlin/dev/httpmarco/polocloud/agent/Agent.kt
agent/src/main/kotlin/dev/httpmarco/polocloud/agent/stats/StatsGrpcService.kt
agent/src/main/kotlin/dev/httpmarco/polocloud/agent/stats/StatsStorageImpl.kt
proto/src/main/proto/polocloud/v1/proto/stats_provider.proto
sdk/sdk-java/src/main/java/dev/httpmarco/polocloud/sdk/java/Polocloud.java
sdk/sdk-java/src/main/java/dev/httpmarco/polocloud/sdk/java/stats/StatsProvider.java
shared/src/main/kotlin/dev/httpmarco/polocloud/shared/PolocloudShared.kt
shared/src/main/kotlin/dev/httpmarco/polocloud/shared/stats/SharedStatsProvider.kt
shared/src/main/kotlin/dev/httpmarco/polocloud/shared/stats/Stats.kt

Added missing attributes
ServiceGrpcService
Rest-API and Proxy Addon
local cloud instance

Added missing attributes in StatsGrpcService

---

addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/bungeecord/commands/InfoSubCommand.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/velocity/subcommands/InfoSubCommand.kt
addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/utils/Format.kt

Implemented missing todo's in proxy addon info command
- Implemented grpc request to get the cloud statistics
/ 
local cloud instance with velocity and paper service

Updated: info command in proxy addon

---

proto/src/main/proto/polocloud/v1/proto/cloud_information_provider.proto
sdk/sdk-java/src/main/java/dev/httpmarco/polocloud/sdk/java/information/CloudInformationProvider.java
shared/src/main/kotlin/dev/httpmarco/polocloud/shared/information/AggregateCloudInformation.kt

…al and cleanup methods
Implemented grpc part for minutes, hours, days caching (CloudInformation)
/
Rest-API (Dashboard)
/ (recher will test it)

Implemented: grpc part for minutes, hours, days caching (CloudInformation)

---

agent/src/main/kotlin/dev/httpmarco/polocloud/agent/grpc/GrpcServerEndpoint.kt
agent/src/main/kotlin/dev/httpmarco/polocloud/agent/logging/LoggerGrpcService.kt
proto/src/main/proto/polocloud/v1/proto/logger_provider.proto
sdk/sdk-java/src/main/java/dev/httpmarco/polocloud/sdk/java/Polocloud.java
sdk/sdk-java/src/main/java/dev/httpmarco/polocloud/sdk/java/logger/LoggerProvider.java

The logger is now available via grpc functions (info, warn, error, debug)
/ 
/ 
local cloud instance (log via velocity plugin)

Implemented: Logging via grpc

---

addons/build.gradle.kts
agent/src/main/kotlin/dev/httpmarco/polocloud/agent/Agent.kt
agent/src/main/kotlin/dev/httpmarco/polocloud/agent/runtime/local/LocalRuntimeFactory.kt
bridges/bridge-api/build.gradle.kts
bridges/bridge-api/src/main/kotlin/dev/httpmarco/polocloud/bridge/api/BridgeInstance.kt
bridges/bridge-bungeecord/build.gradle.kts
bridges/bridge-gate/src/main/kotlin/dev/httpmarco/polocloud/bridges/gate/GateBridge.kt
bridges/bridge-velocity/build.gradle.kts
bridges/bridge-waterdog/build.gradle.kts
bridges/build.gradle.kts
modules/build.gradle.kts
sdk/sdk-java/build.gradle.kts
sdk/sdk-java/src/main/java/dev/httpmarco/polocloud/sdk/java/Polocloud.java
shared/src/main/kotlin/dev/httpmarco/polocloud/shared/PolocloudShared.kt

Fixes issue that polocloudShared does not exists and reverts package update
- setShared was moved to constuctor
- package was changed form 9.0.2 to 9.0.0

Hotfix polocloud shared

---

bridges/bridge-gate/build.gradle.kts
bridges/bridge-gate/src/main/kotlin/dev/httpmarco/polocloud/bridges/gate/GateBridge.kt

Fix gate windows

---

metadata/platforms/pumpkin.json
metadata/tasks/pumpkinSetup.json

New Pumpkin version
- New Commit version of Pumpkin
- Changed setup task to support changed port property

Pumpkin update

---

docs/src/app/(pages)/layout.tsx
docs/src/app/not-found.tsx
docs/src/components/layout/header/home-dropdown.tsx
docs/src/components/ui/dropdown-menu.tsx

fixed footer problem and added 404 page

---

docs/src/app/not-found.tsx
docs/src/components/home/hero/hero-terminal.tsx

…t spacing in HeroTerminal for consistent design

fix: vercel deployment and terminal spacer

---

modules/rest/src/main/kotlin/dev/httpmarco/polocloud/modules/rest/controller/impl/v3/controller/player/PlayerController.kt

impl pagination for players entpoint and fix bug

---

dashboard/src/components/services/service-card.tsx

- Introduced copy-to-clipboard feature for service hostnames with a tooltip guide.
- Added truncation for long hostnames and visual feedback on copy actions.
- Enhanced UI interactivity for improved user experience.

feat(services): add hostname copy functionality with visual feedback

---

dashboard/src/app/api/onboarding/create-admin/route.ts
dashboard/src/app/groups/page.tsx
dashboard/src/app/login/page.tsx
dashboard/src/app/onboarding/components/AdminAccountStep.tsx
dashboard/src/app/onboarding/components/BackendConnectStep.tsx
dashboard/src/app/onboarding/components/OverviewStep.tsx
dashboard/src/app/onboarding/page.tsx
dashboard/src/app/services/page.tsx
dashboard/src/components/app-sidebar.tsx
dashboard/src/components/layout-wrapper.tsx
dashboard/src/components/sidebar/sidebar-footer.tsx
dashboard/src/hooks/useAuth.ts
dashboard/src/lib/auth-credentials.ts
dashboard/src/lib/server-auth-utils.ts

improve: dashboard localstorage

---

dashboard/src/app/api/auth/logout/route.ts
dashboard/src/app/login/page.tsx
dashboard/src/components/app-sidebar.tsx
dashboard/src/components/layout-wrapper.tsx
dashboard/src/hooks/useAuth.ts

- Added cookie clearing for `polocloud_credentials` during logout for enhanced security.
- Introduced cookie setting with credentials during login for persistent session handling.
- Updated `useAuth` and `app-sidebar` to properly handle cookie-based state management.
- Enhanced authentication check to include local storage fallback in layout wrapper.

fix: polocloud_credentials logout and login logic

---

agent/src/main/kotlin/dev/httpmarco/polocloud/agent/runtime/local/LocalRuntimeTemplateStorage.kt
agent/src/main/kotlin/dev/httpmarco/polocloud/agent/runtime/local/LocalTemplate.kt
modules/rest/src/main/kotlin/dev/httpmarco/polocloud/modules/rest/controller/impl/v3/controller/group/GroupController.kt

…rations
- Added error handling with logging for template deletion and size calculation to prevent crashes when files are missing or inaccessible.
- Refactored `delete` method in `LocalRuntimeTemplateStorage` to handle exceptions gracefully and ensure consistent cache updates.
- Enhanced `folderSizeBytes` to return zero on exceptions to avoid miscalculations.

fixing some important bugs 
